# Generated by Django 3.2.6 on 2021-08-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiraTask', '0003_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'to-to'), ('doing', 'doing'), ('done', 'done')], default='to-do', max_length=5),
        ),
    ]
