# Generated by Django 3.2.6 on 2021-08-31 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiraTask', '0004_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('to-do', 'to-do'), ('doing', 'doing'), ('done', 'done')], default='to-do', max_length=5),
        ),
    ]
